/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chain;

public class App {

    public static void main(String[] args) {
        PayRaiseHandler supervisor = new Lähiesimies();
        PayRaiseHandler unitManager = new Yksikönpäällikkö();
        PayRaiseHandler ceo = new CEO();

        supervisor.setNextHandler(unitManager);
        unitManager.setNextHandler(ceo);

        double[] payRaiseRequests = {1, 3, 6};

        for (double request : payRaiseRequests) {
            System.out.println("Työntekijä pyytää " + request + " % palkankorotusta.");
            supervisor.handlePayRaiseRequest(request);
            System.out.println("------");
        }
    }
}
