/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visitor;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull("classUnderTest.getGreeting()", "app should have a greeting");
    }
}
