/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strategy;

public class App {

    public static void main(String[] args) {
        Context c = new Context();
        c.setStrategy(new QuickSort());
        c.sort();
        c.setStrategy(new BubbleSort());
        c.sort();
        c.setStrategy(new MergeSort());
        c.sort();
    }
}
