/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package observer;

public class App {

    public static void main(String[] args) {
        ClockTimer ct = new ClockTimer();

        Ticker ticker = new Ticker(ct);

        DigitalClock dc = new DigitalClock(ct);
        AnalogClock ac = new AnalogClock(ct);

        new Thread(ticker).start();

    }
}
