/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package composite;

import composite.osat.*;
import composite.komposiitit.*;

public class App {

    public static void main(String[] args) {
        
        Emolevy em = new Emolevy(12.30);
        Kotelo kt = new Kotelo(22.40);

        em.lisaaOsa(new Prosessori(100.23));
        em.lisaaOsa(new Verkkokortti(1.23));
        em.lisaaOsa(new Muistipiiri(67.20));
        em.lisaaOsa(new Naytonohjain(2304.56));

        kt.lisaaOsa(em);

        System.out.println(kt.hinta());
        System.out.println("Oha se ny aika siisti");

    }
}
