/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxy;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {
        ArrayList<Image> kansio = new ArrayList<>();
        kansio.add(new ProxyImage("HiRes_10MB_Photo1"));
        kansio.add(new ProxyImage("HiRes_10MB_Photo2"));
        kansio.add(new ProxyImage("HiRes_10MB_Photo3"));
        
        for (Image image : kansio) {
            //näytetään ei ladata
            image.showImage();
        }

        //ladataan
        for (Image image : kansio) {
            //näytetään ei ladata
            image.displayImage();;
        }

    }
}
