/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package template;

public class App {

    public static void main(String[] args) {
        Game peli = new Game();
        peli.playOneGame(2);
    }
}
